### ISSUE TITLE
US highway shields are no just Interstate minus color 

### ISSUE THREAD

**Issue by jidanni** [tracestrack/OpenLayers-Cartographic-Label-Style#1]
At https://www.openstreetmap.org/#map=15/37.8634/-100.5679&layers=P we observe a US Highway bearing an Interstate Highway shield that merely has had color removed.

![Screenshot_20231014-091146.jpg](https://github.com/tracestrack/OpenLayers-Cartographic-Label-Style/assets/1230959/5cfd9199-253c-4ac4-bca5-fa14f18b305f)

No other map I have seen does that. Everybody knows that US highway Shields are shaped somewhat different!

At first view one would assume we are looking at an interstate highway.

It is only after comparison with interstate highways that we figure out that you're just reusing the shields of interstate highways and removing their color has a quick way to label us highways. Please don't. Thanks. 

Also one notices the number could be rather larger, and still not exceed the shield. In other words there's a lot of white space and a small number is being used where a larger one could be.

**Comment by quinncnl** [comment]
Hi @jidanni! Thanks for the feedback. You are right we used a simplified version of interstate shield. Will rework that part.

![Scherm­afbeelding 2023-12-17 om 14 38 15](https://github.com/tracestrack/OpenLayers-Cartographic-Label-Style/assets/359745/50a87e54-becb-4c94-8f11-dc6be67e10bc)

The country specific shields is a big work and we are working to open source it to allow more collaboration on it. You can track it here https://github.com/tracestrack/tracestrack-maps/issues/12.

**Comment by quinncnl** [comment]
Updated shield using https://en.m.wikipedia.org/wiki/File:US_blank.svg

<img width="412" alt="Scherm­afbeelding 2023-12-22 om 21 29 55" src="https://github.com/tracestrack/OpenLayers-Cartographic-Label-Style/assets/359745/305fff92-c5ff-40cf-b91e-227f50fc1caf">
